name: Release Helm Chart
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'
    branches:
      - 'master'


jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish locally in the workspace
        run: |
          echo "ref_type=${{ github.ref_type }}"
          echo "ref_name=${{ github.ref_name }}"
          echo "base_ref=${{ github.event.base_ref }}"
          echo "ref=${{ github.ref }}"

